### ISSUE TITLE
Unknown host problem

### ISSUE THREAD

**Issue by ionutioio** [daveio/whisperpush-unregister#3]
Hello,

First of all, thank you for taking the time to write this script!

I tried running it (on Windows and Ruby 2.0.0) and I have this problem; here is the stack trace:

C:/Ruby200/lib/ruby/2.0.0/net/http.rb:878:in `initialize': getaddrinfo: Hôte inconnu.  (SocketError)
        from C:/Ruby200/lib/ruby/2.0.0/net/http.rb:878:in `open'
        from C:/Ruby200/lib/ruby/2.0.0/net/http.rb:878:in `block in connect'
        from C:/Ruby200/lib/ruby/2.0.0/timeout.rb:52:in `timeout'
        from C:/Ruby200/lib/ruby/2.0.0/net/http.rb:877:in `connect'
        from C:/Ruby200/lib/ruby/2.0.0/net/http.rb:862:in `do_start'
        from C:/Ruby200/lib/ruby/2.0.0/net/http.rb:851:in `start'
        from C:/Ruby200/lib/ruby/2.0.0/net/http.rb:1367:in `request'
        from whisperpush_unregister.rb:27:in `get_code'
        from whisperpush_unregister.rb:130:in `<main>'

Thank you for your kind reply.

**Comment by daveio** [comment]
Closing for inactivity, open a new issue if you're still stuck.
